spec/setup: do not set global.navigator
This was causing the following error on Node v22:

TypeError: Cannot set property navigator of #<Object> which has only a getter

Tests appear to work fine without it.